In [49]:
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats

In [152]:
#The class for a request
class Request:
    def __init__(self, start, end, startTime):
        self.start = start
        self.end = end
        self.startTime = startTime

#The class for each elevator
class Elevator:
    def __init__(self, floor):
        self.currentFloor = floor
        self.passenger = 0
        self.busy = False
    def setRequest(ID):
        self.ID = ID

#The main class which includes all of the functionality for our system.
class Building():
    def __init__(self, numFloors, numElevators):
        self.numElevators = numElevators
        self.numFloors = numFloors
        self.Elevators = [None]*numElevators
        for i in range(len(self.Elevators)):
            self.Elevators[i] = Elevator(np.random.randint(1, self.numFloors+1))
        
        self.Requests = {}
        
    def getFloors(self): #Get the current floor position of each elevator in the building
        self.currentFloors = []
        for i in self.Elevators:
            self.currentFloors += [i.currentFloor]
        return np.array(self.currentFloors)
    
    def dispatch(self, Request, ID): #Assigns a new request to an elevator
        self.Requests[ID] = Request
        tmp = [Request.start] * self.numElevators
        tmp2 = self.getFloors()
        print(self.Elevators[0].busy)
        for i in range(self.numElevators):
            if(self.Elevators[i].busy):
                tmp2[i] = 32767
        waitTime = np.amin(np.abs(tmp2 - tmp))
        print(waitTime)
        print(tmp2-tmp)
        
    #def control(): #Decides how elevators should move. Removes requests if they are finished.
        
    

In [153]:
building = Building(16, 4)
print(building.getFloors())
building.Elevators[0].busy = True

building.dispatch(Request(4, 6, 0), 1)

[ 8 11 10  1]
True
3
[32763     7     6    -3]


True
0
[32762     0     0     0]


In [136]:
def getStartFloor(spec):
    if(spec = "uppeak"):
        xk = np.arange(1,10)
        pk = ()

SyntaxError: invalid syntax (<ipython-input-136-c1f3e049e52c>, line 2)

In [112]:
print(np.array([None, 1, 2, 3]) - np.array([None, 0, 1, 2]))

TypeError: unsupported operand type(s) for -: 'NoneType' and 'NoneType'